[package]
name = "hyper-rustls"
version = "0.21.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dev-dependencies]
async-stream = "0.3.0"
tokio = { version = "0.3", features = ["io-std", "macros", "net", "stream", "rt-multi-thread"] }

[features]
default = ["native-tokio"]
webpki-tokio = ["tokio-runtime", "webpki-roots"]
native-tokio = ["tokio-runtime", "rustls-native-certs"]
tokio-runtime =  ["ct-logs"]

[dependencies]
log = "0.4.4"
ct-logs = { version = "^0.8", optional = true }
futures-util = "0.3.1"
hyper = { version = "0.13.9" }
rustls = "0.19"
rustls-native-certs = { version = "0.5.0", optional = true }
tokio = "0.3.4"
tokio-rustls = "0.21.0"
webpki = "0.21.0"
webpki-roots = { version = "0.21", optional = true }
stub = { path = "../stub" }
blank = '0.1'
