[package]
name = "empty"
version = "0.1.0"
authors = ["Jon Gjengset <jongje@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stub = { path = "../stub/" }
blank = '0.1'
